# Microservice Configuration
server:
  port: 8100

# Spring Configuration
spring:
  application:
    name: netflix
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          # Enable bulk
          batch_size: 1000
        generate_statistics: false
        order_inserts: false
  enable:
    scheduling: true

  datasource:
    url: jdbc:mysql://35.195.96.250:5432/netflix?serverTimezone=UTC&rewriteBatchedStatements=true
    username: postgres
    password: root

# Endpoint microservice exposed
netflix:
  resource:
    version: /v1
    category: /category

