# Microservice Configuration
server:
  port: 8100

# Spring Configuration
spring:
  application:
    name: netflix
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          # Enable bulk
          batch_size: 1000
        generate_statistics: false
        order_inserts: false
  enable:
    scheduling: true

  # Database connection
  datasource:
    url: jdbc:h2:./data/netflix
    driverClassName: org.h2.Driver
    username: root
    password: root
  
  h2:
    console:
      enabled: true

# Endpoint microservice exposed
netflix:
  resource:
    version: /v1
    category: /category

